### ISSUE TITLE
ListController::isCsrfTokenValid() changed and need 2 arguments

### ISSUE THREAD

**Issue by ndoulgeridis** [symfony2admingenerator/AdmingeneratorGeneratorBundle#832] opened 2015-04-15 10:17 UTC
Hello,

I just tried Symfony 2.6.6
After I updated I got this strict standards error.

```
Strict standards: Declaration of ....\ListController::isCsrfTokenValid() should be compatible with Symfony\Bundle\FrameworkBundle\Controller\Controller::isCsrfTokenValid($id, $token) in .....BaseFooController\ListController.php on line 19
```

I think this should be fixed in vendor/cedriclombardot/admingenerator-generator-bundle/Admingenerator/GeneratorBundle/Resources/templates/CommonAdmin/csrf_protection.php.twig

```
{% block csrf_check_token %}

/**
 * Check crsf token provided for action
 *
 * @throw InvalidCsrfTokenException if token is invalid
 */
protected function isCsrfTokenValid($intention)
{
    $token = $this->getRequest()->request->get('_csrf_token');
    if (!$this->get('form.csrf_provider')->isCsrfTokenValid($intention, $token)) {
        throw new InvalidCsrfTokenException();
    }
}

 {% endblock %}
```

I also found many occurrences using

$this->isCsrfTokenValid($intention);

but now this method should have 2 arguments instead

**Comment by ioleo** [comment] 2015-04-15 10:21
Closeing, duplicate of #789. Please see that issue for more info.

**Closed as completed by ioleo** 2015-04-15 10:21 UTC
